# Tutorial 03 — Google Colab and Python (NumPy) + GitHub Integration

In [2]:

# Task 1: Create a numpy array of size 2 x 2
import numpy as np

array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 Array:")
print(array_2x2)


2x2 Array:
[[1 2]
 [3 4]]


In [3]:

# Task 2: Create a random numpy array of size 3 x 4
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 Array:")
print(random_3x4)


Random 3x4 Array:
[[0.65094131 0.48141238 0.56062461 0.63705191]
 [0.72307431 0.19963379 0.07138384 0.52544453]
 [0.76102382 0.82246332 0.59380212 0.4139176 ]]


In [4]:

# Task 3: Create numpy arrays of ones and zeroes
ones_array = np.ones((2, 3))
zeros_array = np.zeros((2, 3))

print("Array of Ones:")
print(ones_array)
print("\nArray of Zeroes:")
print(zeros_array)


Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Array of Zeroes:
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:

# Task 4: Create a random numpy array of size 6x3 and transpose it
rand_6x3 = np.random.randint(1, 10, (6, 3))
print("Original 6x3 Array:")
print(rand_6x3)

transposed = rand_6x3.T
print("\nTransposed Array (3x6):")
print(transposed)


Original 6x3 Array:
[[8 8 3]
 [5 1 6]
 [8 5 2]
 [8 6 9]
 [1 2 5]
 [6 1 5]]

Transposed Array (3x6):
[[8 5 8 8 1 6]
 [8 1 5 6 2 1]
 [3 6 2 9 5 5]]
