# Tutorial 03 — Google Colab and Python (NumPy) + GitHub Integration

In [2]:

# Task 1: Create a numpy array of size 2 x 2
import numpy as np

array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 Array:")
print(array_2x2)


2x2 Array:
[[1 2]
 [3 4]]


In [3]:

# Task 2: Create a random numpy array of size 3 x 4
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 Array:")
print(random_3x4)


Random 3x4 Array:
[[0.65094131 0.48141238 0.56062461 0.63705191]
 [0.72307431 0.19963379 0.07138384 0.52544453]
 [0.76102382 0.82246332 0.59380212 0.4139176 ]]
